### ISSUE TITLE
Does not work on linux

### ISSUE THREAD

**Issue by khayyamsaleem** [benwaffle/doc#3]
panics immediately:

```
➜  doc git:(main) ./doc ls          
/usr/share/man/man1/ls.1.gz
panic: runtime error: slice bounds out of range [4:3]

goroutine 1 [running]:
main.parseMdoc({0xc000280000, 0x1f71})
	/home/ksaleem/dev/personal/doc/doc.go:401 +0x42b2
main.main()
	/home/ksaleem/dev/personal/doc/doc.go:590 +0x1ee
```

**Comment by benwaffle** [comment]
embarrassing
